services:
  frontend:
    image: nginx:alpine
    ports:
      - "443:8043"
    networks:
      - front-tier
      - back-tier
    # 本地配置文件只读挂载
    volumes:
      # 网页代码
      - ./web-html:/usr/share/nginx/html:ro
      # Nginx配置
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # HTTPS证书只读挂载
      - ./cert:/etc/ssl/cert:ro

  backend:
    image: mysql:8.0
    volumes:
      # 持久化数据卷
      - db-data:/var/lib/mysql
    networks:
      - back-tier
    environment:
      MYSQL_ROOT_PASSWORD: "root123456"
      MYSQL_DATABASE: "test_db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    restart: always

# 持久化数据卷
volumes:
  db-data:
    driver: local

# 双层隔离网络
networks:
  front-tier: {}
  back-tier: {}