server {
    listen       8043 ssl;
    server_name  localhost;

    # 容器内证书挂载路径
    ssl_certificate     /etc/ssl/cert/server.crt;
    ssl_certificate_key /etc/ssl/cert/server.key;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }
}
