apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: test
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data # 和下方volumes.name保持一致
              mountPath: /var/lib/mysql # MySQL默认数据存放目录，必须挂载这里
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql # 关键：service名称=mysql，代码DSN才能解析
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc # deployment引用这个名字
spec:
  accessModes:
    - ReadWriteOnce # 单节点读写，kind集群固定用这个
  resources:
    requests:
      storage: 1Gi # 分配1G持久化存储空间，测试足够