apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # 值必须base64编码
  # root -> echo -n root | base64
  MYSQL_USER: cm9vdA==
  # root -> echo -n root | base64
  MYSQL_PASS: cm9vdA==