# 编译阶段镜像
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o app ./cmd

# 运行阶段镜像
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/app .

CMD ["./app"]